import type { Metadata } from "next";
import localFont from "next/font/local";
import "./../globals.css";
import { Toaster } from "@/components/ui/toaster";
import { FileIcon, StarIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="container mx-auto pt-12 ">
    <div className="flex gap-8">
      <div className="w-36 flex flex-col gap-4 " >
        <Link href="/dashboard/files">  
          <Button variant="link" className="flex gap-2" >
            <FileIcon /> All Files
          </Button>
        </Link>
        <Link href="/dashboard/favorites">  
          <Button variant="link" className="flex gap-2" >
            <StarIcon /> Favorites
          </Button>
        </Link>
      </div>

      <div className="w-full" >
        {children}
       </div>
    </div>
  </div>
  );
}
