import type { Metadata } from "next";
import localFont from "next/font/local";
import "./../globals.css";
import { SideNav } from "./SideNav";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="container mx-auto pt-12 ">
    <div className="main-layout flex gap-8">
      <div className="section-1 w-36 flex flex-col gap-4 " >
       <SideNav/>
      </div>

      <div className="section-2 w-full" >
        {children}
       </div>
    </div>
  </div>
  );
}
